name: Test

on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest & Mac Os
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm test
